//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guitar
    {
        public int Id { get; set; }
        public string Maker { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public int Year { get; set; }
        public System.DateTime AddDate { get; set; }
        public int ConditionId { get; set; }
        public int GuitarTypeId { get; set; }
        public string ImageURL { get; set; }
        public bool RotateImage { get; set; }
        public int Price { get; set; }
        public bool Sold { get; set; }
        public int SellerId { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual GuitarType GuitarType { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
